services:
  - type: web
    name: render-web-app
    env: python
    plan: free
    buildCommand: "pip install -r src/main/requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: render-web-app-db
          property: connectionString
  - type: postgresql
    name: render-web-app-db
    plan: free
